"use client";

import { z } from "zod";
import { lintDeck, type SlideDiagnostic } from "./lint-deck";
import { normalizeDeck, type DeckAssetResolver, type DeckFill, type SlideDeck, type SlideElement } from "./slides";
import { useFilesystemStore } from "@/app/store/filesystem";
import { useCanvasStore } from "@/app/store/canvas";

const PAGE_SIZE = 20;
const pageSchema = { offset: z.number().int().min(0).optional(), limit: z.number().int().min(1).max(PAGE_SIZE).optional() };
const boxSchema = z.object({ x: z.number(), y: z.number(), width: z.number().positive(), height: z.number().positive() });
const fillSchema = z.object({ color: z.string(), opacity: z.number().min(0).max(1).optional() }).optional();
const strokeSchema = z.object({ color: z.string(), width: z.number().nonnegative().optional(), opacity: z.number().min(0).max(1).optional(), dash: z.enum(["solid", "dash", "dot", "dashDot"]).optional() }).optional();
const textStyleSchema = z.object({ fontFamily: z.string().optional(), fontSize: z.number().positive().optional(), color: z.string().optional(), bold: z.boolean().optional(), italic: z.boolean().optional(), underline: z.boolean().optional(), align: z.enum(["left", "center", "right", "justify"]).optional(), verticalAlign: z.enum(["top", "middle", "bottom"]).optional(), lineSpacing: z.number().positive().optional(), letterSpacing: z.number().optional(), margin: z.union([z.number(), z.tuple([z.number(), z.number(), z.number(), z.number()])]).optional(), bullet: z.union([z.boolean(), z.object({ indent: z.number().optional(), hanging: z.number().optional() })]).optional() }).optional();

interface PresentationOutline {
  version: 1; deckPath: string; name: string; audience: string; objective: string; visualDirection?: string;
  slides: Array<{ id: string; title: string; purpose: string; keyPoints: string[]; layoutHint?: string }>;
}

function pathSegments(path: string) { const parts = path.split("/").filter(Boolean); if (!parts.length || parts.some((part) => part === "." || part === "..")) throw new Error("Use a non-empty workspace path without . or .. segments."); return parts; }
async function readFile(path: string) { const parts = pathSegments(path); return useFilesystemStore.getState().readFileAt(parts.slice(0, -1), parts.at(-1)!); }
async function writeFile(path: string, data: BlobPart, type: string) { const parts = pathSegments(path); if (parts[0] === "Uploads") throw new Error("Uploads is read-only."); await useFilesystemStore.getState().uploadFilesTo(parts.slice(0, -1), [new File([data], parts.at(-1)!, { type })]); }
const assetResolver: DeckAssetResolver = async (source) => /^(data:image\/|blob:|https?:\/\/)/i.test(source) ? source : readFile(source).catch(() => null);
async function loadDeck(path: string) { return normalizeDeck(await (await readFile(path)).text()).deck; }
async function saveDeck(path: string, deck: SlideDeck) { await writeFile(path, JSON.stringify(deck, null, 2), "application/json"); }
function syncOpenDeck(path: string, deck: SlideDeck) {
  const canvas = useCanvasStore.getState();
  if (canvas.kind === "deck" && canvas.deckPath === path) canvas.updateDeck(deck);
}
function page<T>(items: readonly T[], offset: number, limit: number) { return { total: items.length, offset, limit, items: items.slice(offset, offset + limit), hasMore: offset + limit < items.length }; }
function truncate(value: string, max = 120) { return value.length > max ? `${value.slice(0, max - 1)}…` : value; }
function diagnostic(d: SlideDiagnostic) { return { code: d.code, message: d.message, slideId: d.slideId, elementId: d.elementId }; }
function sourceDescriptor(src: string) { if (/^data:/i.test(src)) return "<inline image>"; return src.split("/").at(-1) || src; }
function objectOnly(value: unknown, field: string): Record<string, unknown> {
  if (typeof value === "string") throw new Error(`${field} must be a JSON object, not a JSON-encoded string.`);
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(`${field} must be a JSON object.`);
  return value as Record<string, unknown>;
}
function strictElementFields(input: Record<string, unknown>, fields: Array<"box" | "style" | "textStyle" | "fill" | "stroke" | "crop">) {
  const output = { ...input };
  for (const field of fields) {
    if (output[field] === undefined) continue;
    const value = objectOnly(output[field], field);
    if (field === "box") output.box = boxSchema.parse(value);
    else if (field === "style" || field === "textStyle") output[field] = textStyleSchema.parse(value);
    else if (field === "fill") output.fill = fillSchema.parse(value);
    else if (field === "stroke") output.stroke = strokeSchema.parse(value);
    else output.crop = z.object({ left: z.number().optional(), right: z.number().optional(), top: z.number().optional(), bottom: z.number().optional() }).parse(value);
  }
  return output;
}
function indexElement(element: SlideElement) { const text = element.type === "text" ? element.text : element.type === "shape" ? element.text : undefined; return { id: element.id, type: element.type, name: element.name, box: element.box, ...(text ? { textPreview: truncate(text) } : {}), ...(element.type === "image" ? { assetName: sourceDescriptor(element.src) } : {}) }; }
function detailElement(element: SlideElement) { return element.type === "image" && /^data:/i.test(element.src) ? { ...element, src: "<inline image omitted>", sourceKind: "inline" } : element; }
function slideIndex(deck: SlideDeck, slideId: string) { const index = deck.slides.findIndex((slide) => slide.id === slideId); if (index < 0) throw new Error(`Slide ${JSON.stringify(slideId)} does not exist.`); return index; }
function unique(deck: SlideDeck, id: string, kind: string) { if (deck.slides.some((s) => s.id === id) || deck.slides.some((s) => s.elements.some((e) => e.id === id))) throw new Error(`${kind} ID ${JSON.stringify(id)} is already in use.`); }
async function validateMutation(path: string, deck: SlideDeck) { const normalized = normalizeDeck(deck); const diagnostics = await lintDeck(normalized.deck, { assetResolver }); const errors = [...normalized.issues.filter((issue) => issue.severity === "error"), ...diagnostics.filter((issue) => issue.severity === "error")]; if (errors.length) throw new Error(`Deck mutation rejected: ${errors.map((error) => error.message).join(" ")}`); await saveDeck(path, normalized.deck); syncOpenDeck(path, normalized.deck); return { deck: normalized.deck, diagnostics }; }
function mutationResult(path: string, diagnostics: SlideDiagnostic[], slideId?: string, elementId?: string, index?: number) { const warnings = diagnostics.filter((d) => d.severity === "warning"); const affectedWarnings = warnings.filter((d) => (!slideId || d.slideId === slideId) && (!elementId || d.elementId === elementId)).map(diagnostic); return { ok: true, path, ...(slideId ? { slideId } : {}), ...(elementId ? { elementId } : {}), ...(index === undefined ? {} : { index }), warningCount: warnings.length, affectedWarnings }; }

const briefSchema = z.object({ id: z.string().min(1).max(80), title: z.string().min(1).max(120), purpose: z.string().min(1).max(240), keyPoints: z.array(z.string().min(1).max(180)).min(1).max(4), layoutHint: z.string().max(120).optional() });
export const createPresentationOutlineTool = { toolName: "create_presentation_outline", type: "frontend" as const, description: "Save concise ordered slide briefs before authoring a deck. The path must be a complete JSON file path, not a directory.", parameters: z.object({ path: z.string().describe('Complete destination filename ending in ".outline.json", for example "Outputs/dogs.outline.json". Never pass a directory such as "Outputs".'), deckPath: z.string().describe('Complete destination filename for the presentation deck ending in ".slides.json", for example "Outputs/dogs.slides.json".'), name: z.string().min(1).max(120), audience: z.string().min(1).max(240), objective: z.string().min(1).max(240), visualDirection: z.string().max(240).optional(), slides: z.array(briefSchema).min(1) }), execute: async ({ path, ...outline }: Omit<PresentationOutline, "version"> & { path: string }) => { if (new Set(outline.slides.map((slide) => slide.id)).size !== outline.slides.length) throw new Error("Outline slide IDs must be unique."); await writeFile(path, JSON.stringify({ version: 1, ...outline }, null, 2), "application/json"); return { ok: true, path, deckPath: outline.deckPath, slideCount: outline.slides.length }; } };
export const getPresentationOutlineTool = { toolName: "get_presentation_outline", type: "frontend" as const, description: "Get a paginated compact index of an outline's slide briefs.", parameters: z.object({ path: z.string(), ...pageSchema }), execute: async ({ path, offset = 0, limit = PAGE_SIZE }: { path: string; offset?: number; limit?: number }) => { const outline = JSON.parse(await (await readFile(path)).text()) as PresentationOutline; return { path, deckPath: outline.deckPath, name: outline.name, audience: outline.audience, objective: outline.objective, visualDirection: outline.visualDirection, slides: page(outline.slides.map((slide, index) => ({ index: index + 1, id: slide.id, title: slide.title, layoutHint: slide.layoutHint })), offset, limit) }; } };
export const getPresentationOutlineSlideTool = { toolName: "get_presentation_outline_slide", type: "frontend" as const, description: "Get one concise outline brief by slide ID.", parameters: z.object({ path: z.string(), slideId: z.string() }), execute: async ({ path, slideId }: { path: string; slideId: string }) => { const outline = JSON.parse(await (await readFile(path)).text()) as PresentationOutline; const slide = outline.slides.find((item) => item.id === slideId); if (!slide) throw new Error(`Outline slide ${JSON.stringify(slideId)} does not exist.`); return { path, slide }; } };

export const getDeckSummaryTool = { toolName: "get_deck_summary", type: "frontend" as const, description: "Get deck metadata and a paginated slide index; never returns deck JSON.", parameters: z.object({ path: z.string(), ...pageSchema }), execute: async ({ path, offset = 0, limit = PAGE_SIZE }: { path: string; offset?: number; limit?: number }) => { const deck = await loadDeck(path); return { path, id: deck.id, name: deck.name, size: deck.size, theme: { name: deck.theme.name, colors: deck.theme.colors, fonts: deck.theme.fonts, background: deck.theme.background }, template: deck.template ? { name: deck.template.manifest.name, sourcePath: deck.template.sourcePath, layoutCount: deck.template.manifest.layouts.length } : null, slides: page(deck.slides.map((slide, index) => ({ index: index + 1, id: slide.id, name: slide.name, layoutId: slide.layoutId, elementCount: slide.elements.length })), offset, limit) }; } };
export const getSlideIndexTool = { toolName: "get_slide_index", type: "frontend" as const, description: "Get one slide's metadata and a paginated compact element index.", parameters: z.object({ path: z.string(), slideId: z.string(), ...pageSchema }), execute: async ({ path, slideId, offset = 0, limit = PAGE_SIZE }: { path: string; slideId: string; offset?: number; limit?: number }) => { const deck = await loadDeck(path); const slide = deck.slides[slideIndex(deck, slideId)]; return { path, slide: { id: slide.id, name: slide.name, layoutId: slide.layoutId, background: slide.background, hidden: slide.hidden, elementCount: slide.elements.length }, elements: page(slide.elements.map(indexElement), offset, limit) }; } };
export const getSlideElementTool = { toolName: "get_slide_element", type: "frontend" as const, description: "Get one element's editable fields. Inline image bytes are always redacted.", parameters: z.object({ path: z.string(), slideId: z.string(), elementId: z.string() }), execute: async ({ path, slideId, elementId }: { path: string; slideId: string; elementId: string }) => { const deck = await loadDeck(path); const slide = deck.slides[slideIndex(deck, slideId)]; const element = slide.elements.find((item) => item.id === elementId); if (!element) throw new Error(`Element ${JSON.stringify(elementId)} does not exist on this slide.`); return { path, slideId, element: detailElement(element) }; } };
export const listSlideLayoutsTool = { toolName: "list_slide_layouts", type: "frontend" as const, description: "Get a paginated template layout index without placeholder payloads.", parameters: z.object({ path: z.string(), ...pageSchema }), execute: async ({ path, offset = 0, limit = PAGE_SIZE }: { path: string; offset?: number; limit?: number }) => { const deck = await loadDeck(path); const layouts = deck.template?.manifest.layouts ?? []; return { path, layouts: page(layouts.map((layout) => ({ id: layout.id, name: layout.name, type: layout.type, placeholderCount: layout.placeholders.length })), offset, limit) }; } };
export const getSlideLayoutTool = { toolName: "get_slide_layout", type: "frontend" as const, description: "Get placeholders for one selected template layout; inherited artwork is omitted.", parameters: z.object({ path: z.string(), layoutId: z.string() }), execute: async ({ path, layoutId }: { path: string; layoutId: string }) => { const deck = await loadDeck(path); const layout = deck.template?.manifest.layouts.find((item) => item.id === layoutId); if (!layout) throw new Error(`Template layout ${JSON.stringify(layoutId)} does not exist.`); return { path, layout: { id: layout.id, name: layout.name, type: layout.type, background: layout.background, placeholders: layout.placeholders } }; } };

export const addSlideTool = { toolName: "add_slide", type: "frontend" as const, description: "Add a named empty slide after an optional existing slide.", parameters: z.object({ path: z.string(), id: z.string(), name: z.string(), afterSlideId: z.string().optional(), layoutId: z.string().optional(), background: fillSchema, notes: z.string().optional() }), execute: async ({ path, afterSlideId, ...slide }: { path: string; afterSlideId?: string; id: string; name: string; layoutId?: string; background?: DeckFill; notes?: string }) => { const deck = await loadDeck(path); unique(deck, slide.id, "Slide"); const index = afterSlideId ? slideIndex(deck, afterSlideId) + 1 : deck.slides.length; deck.slides.splice(index, 0, { ...slide, elements: [] }); const saved = await validateMutation(path, deck); return mutationResult(path, saved.diagnostics, slide.id, undefined, index); } };
export const updateSlideTool = { toolName: "update_slide", type: "frontend" as const, description: "Update one slide's metadata or layout.", parameters: z.object({ path: z.string(), slideId: z.string(), name: z.string().optional(), layoutId: z.string().nullable().optional(), background: fillSchema.nullable().optional(), notes: z.string().nullable().optional(), hidden: z.boolean().optional() }), execute: async ({ path, slideId, ...patch }: { path: string; slideId: string; [key: string]: unknown }) => { const deck = await loadDeck(path); const index = slideIndex(deck, slideId); deck.slides[index] = { ...deck.slides[index], ...patch, ...(patch.layoutId === null ? { layoutId: undefined } : {}), ...(patch.background === null ? { background: undefined } : {}), ...(patch.notes === null ? { notes: undefined } : {}) }; const saved = await validateMutation(path, deck); return mutationResult(path, saved.diagnostics, slideId, undefined, index); } };
export const moveSlideTool = { toolName: "move_slide", type: "frontend" as const, description: "Move a slide before another slide, or to the end.", parameters: z.object({ path: z.string(), slideId: z.string(), beforeSlideId: z.string().optional() }), execute: async ({ path, slideId, beforeSlideId }: { path: string; slideId: string; beforeSlideId?: string }) => { const deck = await loadDeck(path); const from = slideIndex(deck, slideId); const [slide] = deck.slides.splice(from, 1); const index = beforeSlideId ? slideIndex(deck, beforeSlideId) : deck.slides.length; deck.slides.splice(index, 0, slide); const saved = await validateMutation(path, deck); return mutationResult(path, saved.diagnostics, slideId, undefined, index); } };
export const deleteSlideTool = { toolName: "delete_slide", type: "frontend" as const, description: "Delete one slide; a deck must retain one slide.", parameters: z.object({ path: z.string(), slideId: z.string() }), execute: async ({ path, slideId }: { path: string; slideId: string }) => { const deck = await loadDeck(path); if (deck.slides.length === 1) throw new Error("A deck must retain at least one slide."); const index = slideIndex(deck, slideId); deck.slides.splice(index, 1); const saved = await validateMutation(path, deck); return mutationResult(path, saved.diagnostics, slideId, undefined, index); } };
export const duplicateSlideTool = { toolName: "duplicate_slide", type: "frontend" as const, description: "Duplicate a slide after itself with unique element IDs.", parameters: z.object({ path: z.string(), slideId: z.string(), newSlideId: z.string(), name: z.string().optional() }), execute: async ({ path, slideId, newSlideId, name }: { path: string; slideId: string; newSlideId: string; name?: string }) => { const deck = await loadDeck(path); unique(deck, newSlideId, "Slide"); const source = deck.slides[slideIndex(deck, slideId)]; const index = slideIndex(deck, slideId) + 1; deck.slides.splice(index, 0, { ...source, id: newSlideId, name: name ?? `${source.name ?? "Slide"} copy`, elements: source.elements.map((element) => ({ ...element, id: `${newSlideId}-${element.id}` })) }); const saved = await validateMutation(path, deck); return mutationResult(path, saved.diagnostics, newSlideId, undefined, index); } };

async function addElement(path: string, slideId: string, element: SlideElement) { const deck = await loadDeck(path); unique(deck, element.id, "Element"); const slideAt = slideIndex(deck, slideId); deck.slides[slideAt] = { ...deck.slides[slideAt], elements: [...deck.slides[slideAt].elements, element] }; const saved = await validateMutation(path, deck); return mutationResult(path, saved.diagnostics, slideId, element.id); }
const commonElement = { path: z.string(), slideId: z.string(), id: z.string(), name: z.string().optional(), box: boxSchema, zIndex: z.number().optional(), rotation: z.number().optional(), opacity: z.number().min(0).max(1).optional(), locked: z.boolean().optional(), placeholderId: z.string().optional() };
export const addTextElementTool = { toolName: "add_text_element", type: "frontend" as const, description: "Add editable text. box is a 0–100 JSON object ({x,y,width,height}); style is a JSON object, never an encoded string.", parameters: z.object({ ...commonElement, text: z.string(), style: textStyleSchema, fill: fillSchema, stroke: strokeSchema }), execute: async ({ path, slideId, ...element }: { path: string; slideId: string; [key: string]: unknown }) => addElement(path, slideId, { ...strictElementFields(element, ["box", "style", "fill", "stroke"]), type: "text" } as SlideElement) };
export const fillTextPlaceholderTool = { toolName: "fill_text_placeholder", type: "frontend" as const, description: "Fill one template text placeholder using its inherited geometry and style.", parameters: z.object({ path: z.string(), slideId: z.string(), placeholderId: z.string(), id: z.string(), text: z.string(), name: z.string().optional(), style: textStyleSchema }), execute: async ({ path, slideId, placeholderId, id, text, name, style }: { path: string; slideId: string; placeholderId: string; id: string; text: string; name?: string; style?: Record<string, unknown> }) => { const deck = await loadDeck(path); unique(deck, id, "Element"); const slideAt = slideIndex(deck, slideId); const slide = deck.slides[slideAt]; const layout = deck.template?.manifest.layouts.find((item) => item.id === slide.layoutId); if (!layout) throw new Error("The slide does not use a template layout."); const placeholder = layout.placeholders.find((item) => item.id === placeholderId); if (!placeholder?.box) throw new Error(`Placeholder ${JSON.stringify(placeholderId)} has no resolved geometry.`); if (["pic", "ftr", "dt", "sldNum", "hdr"].includes(placeholder.type ?? "")) throw new Error("This placeholder does not accept authored text."); if (slide.elements.some((element) => element.placeholderId === placeholderId)) throw new Error(`Placeholder ${JSON.stringify(placeholderId)} is already filled.`); const type = placeholder.type ?? "body"; const fontSize = type === "title" || type === "ctrTitle" ? 32 : type === "subTitle" ? 22 : 18; const element: SlideElement = { id, type: "text", name: name ?? placeholder.name ?? type, box: placeholder.box, text, placeholderId, style: { ...placeholder.textStyle, fontSize, ...(style ?? {}) } }; deck.slides[slideAt] = { ...slide, elements: [...slide.elements, element] }; const saved = await validateMutation(path, deck); return mutationResult(path, saved.diagnostics, slideId, id); } };
export const addShapeElementTool = { toolName: "add_shape_element", type: "frontend" as const, description: "Add an editable PowerPoint shape. Structured fields must be JSON objects, never encoded strings.", parameters: z.object({ ...commonElement, shape: z.enum(["rect", "roundRect", "ellipse", "triangle", "diamond", "line", "arrow", "chevron", "hexagon", "parallelogram"]), text: z.string().optional(), textStyle: textStyleSchema, fill: fillSchema, stroke: strokeSchema }), execute: async ({ path, slideId, ...element }: { path: string; slideId: string; [key: string]: unknown }) => addElement(path, slideId, { ...strictElementFields(element, ["box", "textStyle", "fill", "stroke"]), type: "shape" } as SlideElement) };
export const addImageElementTool = { toolName: "add_image_element", type: "frontend" as const, description: "Add a workspace or data-URL image. box and crop must be JSON objects, never encoded strings.", parameters: z.object({ ...commonElement, src: z.string(), alt: z.string().min(1), fit: z.enum(["contain", "cover", "stretch"]).optional(), crop: z.object({ left: z.number().optional(), right: z.number().optional(), top: z.number().optional(), bottom: z.number().optional() }).optional() }), execute: async ({ path, slideId, ...element }: { path: string; slideId: string; [key: string]: unknown }) => addElement(path, slideId, { ...strictElementFields(element, ["box", "crop"]), type: "image" } as SlideElement) };
export const addLineElementTool = { toolName: "add_line_element", type: "frontend" as const, description: "Add a line or connector. box and stroke must be JSON objects, never encoded strings.", parameters: z.object({ ...commonElement, stroke: strokeSchema, beginArrow: z.enum(["none", "triangle", "stealth", "oval"]).optional(), endArrow: z.enum(["none", "triangle", "stealth", "oval"]).optional() }), execute: async ({ path, slideId, ...element }: { path: string; slideId: string; [key: string]: unknown }) => addElement(path, slideId, { ...strictElementFields(element, ["box", "stroke"]), type: "line" } as SlideElement) };
export const updateSlideElementTool = { toolName: "update_slide_element", type: "frontend" as const, description: "Patch one element without changing its type or ID. Structured fields must be JSON objects, never encoded strings.", parameters: z.object({ path: z.string(), slideId: z.string(), elementId: z.string(), patch: z.record(z.string(), z.unknown()) }), execute: async ({ path, slideId, elementId, patch }: { path: string; slideId: string; elementId: string; patch: Record<string, unknown> }) => { if ("id" in patch || "type" in patch) throw new Error("Element ID and type are immutable."); const deck = await loadDeck(path); const slideAt = slideIndex(deck, slideId); const elementAt = deck.slides[slideAt].elements.findIndex((element) => element.id === elementId); if (elementAt < 0) throw new Error(`Element ${JSON.stringify(elementId)} does not exist on this slide.`); const elements = [...deck.slides[slideAt].elements]; elements[elementAt] = { ...elements[elementAt], ...strictElementFields(patch, ["box", "style", "textStyle", "fill", "stroke", "crop"]) } as SlideElement; deck.slides[slideAt] = { ...deck.slides[slideAt], elements }; const saved = await validateMutation(path, deck); return mutationResult(path, saved.diagnostics, slideId, elementId); } };
export const deleteSlideElementTool = { toolName: "delete_slide_element", type: "frontend" as const, description: "Delete one element from a slide.", parameters: z.object({ path: z.string(), slideId: z.string(), elementId: z.string() }), execute: async ({ path, slideId, elementId }: { path: string; slideId: string; elementId: string }) => { const deck = await loadDeck(path); const slideAt = slideIndex(deck, slideId); const elements = deck.slides[slideAt].elements.filter((element) => element.id !== elementId); if (elements.length === deck.slides[slideAt].elements.length) throw new Error(`Element ${JSON.stringify(elementId)} does not exist on this slide.`); deck.slides[slideAt] = { ...deck.slides[slideAt], elements }; const saved = await validateMutation(path, deck); return mutationResult(path, saved.diagnostics, slideId, elementId); } };
